# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/School/UIUC_ECE385_SP25/Final_Project/Final_Project.srcs/sources_1/bd/mb_lab7_1/ip/mb_lab7_1_lmb_bram_0/mb_lab7_1_lmb_bram_0.xci
# IP: The module: 'mb_lab7_1_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/School/UIUC_ECE385_SP25/Final_Project/Final_Project.gen/sources_1/bd/mb_lab7_1/ip/mb_lab7_1_lmb_bram_0/mb_lab7_1_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_lab7_1_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/School/UIUC_ECE385_SP25/Final_Project/Final_Project.srcs/sources_1/bd/mb_lab7_1/ip/mb_lab7_1_lmb_bram_0/mb_lab7_1_lmb_bram_0.xci
# IP: The module: 'mb_lab7_1_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/School/UIUC_ECE385_SP25/Final_Project/Final_Project.gen/sources_1/bd/mb_lab7_1/ip/mb_lab7_1_lmb_bram_0/mb_lab7_1_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_lab7_1_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
