# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/School/UIUC_ECE385_SP25/lab7_1/lab7_1.srcs/sources_1/bd/mb_lab7_1/ip/mb_lab7_1_hdmi_text_controller_0_0/mb_lab7_1_hdmi_text_controller_0_0.xci
# IP: The module: 'mb_lab7_1_hdmi_text_controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/School/UIUC_ECE385_SP25/lab7_1/lab7_1.gen/sources_1/bd/mb_lab7_1/ip/mb_lab7_1_hdmi_text_controller_0_0/src/hdmi_tx_0_1/hdmi_tx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_0 || ORIG_REF_NAME==hdmi_tx_0} -quiet] -quiet

# IP: d:/School/UIUC_ECE385_SP25/lab7_1/lab7_1.gen/sources_1/bd/mb_lab7_1/ip/mb_lab7_1_hdmi_text_controller_0_0/src/clk_wiz_0_1/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: d:/School/UIUC_ECE385_SP25/lab7_1/lab7_1.gen/sources_1/bd/mb_lab7_1/ip/mb_lab7_1_hdmi_text_controller_0_0/src/clk_wiz_0_1/clk_wiz_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/School/UIUC_ECE385_SP25/lab7_1/lab7_1.gen/sources_1/bd/mb_lab7_1/ip/mb_lab7_1_hdmi_text_controller_0_0/src/clk_wiz_0_1/clk_wiz_0_ooc.xdc

# IP: D:/School/UIUC_ECE385_SP25/lab7_1/lab7_1.srcs/sources_1/bd/mb_lab7_1/ip/mb_lab7_1_hdmi_text_controller_0_0/mb_lab7_1_hdmi_text_controller_0_0.xci
# IP: The module: 'mb_lab7_1_hdmi_text_controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/School/UIUC_ECE385_SP25/lab7_1/lab7_1.gen/sources_1/bd/mb_lab7_1/ip/mb_lab7_1_hdmi_text_controller_0_0/src/hdmi_tx_0_1/hdmi_tx_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_0 || ORIG_REF_NAME==hdmi_tx_0} -quiet] -quiet

# IP: d:/School/UIUC_ECE385_SP25/lab7_1/lab7_1.gen/sources_1/bd/mb_lab7_1/ip/mb_lab7_1_hdmi_text_controller_0_0/src/clk_wiz_0_1/clk_wiz_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: d:/School/UIUC_ECE385_SP25/lab7_1/lab7_1.gen/sources_1/bd/mb_lab7_1/ip/mb_lab7_1_hdmi_text_controller_0_0/src/clk_wiz_0_1/clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/School/UIUC_ECE385_SP25/lab7_1/lab7_1.gen/sources_1/bd/mb_lab7_1/ip/mb_lab7_1_hdmi_text_controller_0_0/src/clk_wiz_0_1/clk_wiz_0_ooc.xdc
