# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/pin_assignment/mb_usb_hdmi_top.xdc

# Block Designs: bd/mb_lab7_1/mb_lab7_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab7_1 || ORIG_REF_NAME==mb_lab7_1} -quiet] -quiet

# IP: bd/mb_lab7_1/ip/mb_lab7_1_microblaze_0_0/mb_lab7_1_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab7_1_microblaze_0_0 || ORIG_REF_NAME==mb_lab7_1_microblaze_0_0} -quiet] -quiet

# IP: bd/mb_lab7_1/ip/mb_lab7_1_dlmb_v10_0/mb_lab7_1_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab7_1_dlmb_v10_0 || ORIG_REF_NAME==mb_lab7_1_dlmb_v10_0} -quiet] -quiet

# IP: bd/mb_lab7_1/ip/mb_lab7_1_ilmb_v10_0/mb_lab7_1_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab7_1_ilmb_v10_0 || ORIG_REF_NAME==mb_lab7_1_ilmb_v10_0} -quiet] -quiet

# IP: bd/mb_lab7_1/ip/mb_lab7_1_dlmb_bram_if_cntlr_0/mb_lab7_1_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab7_1_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_lab7_1_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_lab7_1/ip/mb_lab7_1_ilmb_bram_if_cntlr_0/mb_lab7_1_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab7_1_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_lab7_1_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_lab7_1/ip/mb_lab7_1_lmb_bram_0/mb_lab7_1_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab7_1_lmb_bram_0 || ORIG_REF_NAME==mb_lab7_1_lmb_bram_0} -quiet] -quiet

# IP: bd/mb_lab7_1/ip/mb_lab7_1_xbar_0/mb_lab7_1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab7_1_xbar_0 || ORIG_REF_NAME==mb_lab7_1_xbar_0} -quiet] -quiet

# IP: bd/mb_lab7_1/ip/mb_lab7_1_microblaze_0_axi_periph_0/mb_lab7_1_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab7_1_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb_lab7_1_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/mb_lab7_1/ip/mb_lab7_1_microblaze_0_axi_intc_0/mb_lab7_1_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab7_1_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_lab7_1_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/mb_lab7_1/ip/mb_lab7_1_mdm_1_0/mb_lab7_1_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab7_1_mdm_1_0 || ORIG_REF_NAME==mb_lab7_1_mdm_1_0} -quiet] -quiet

# IP: bd/mb_lab7_1/ip/mb_lab7_1_clk_wiz_1_0/mb_lab7_1_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab7_1_clk_wiz_1_0 || ORIG_REF_NAME==mb_lab7_1_clk_wiz_1_0} -quiet] -quiet

# IP: bd/mb_lab7_1/ip/mb_lab7_1_rst_clk_wiz_1_100M_0/mb_lab7_1_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab7_1_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mb_lab7_1_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/mb_lab7_1/ip/mb_lab7_1_axi_uartlite_0_0/mb_lab7_1_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab7_1_axi_uartlite_0_0 || ORIG_REF_NAME==mb_lab7_1_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mb_lab7_1/ip/mb_lab7_1_hdmi_text_controller_0_0/mb_lab7_1_hdmi_text_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_lab7_1_hdmi_text_controller_0_0 || ORIG_REF_NAME==mb_lab7_1_hdmi_text_controller_0_0} -quiet] -quiet

# XDC: d:/School/UIUC_ECE385_SP25/lab7_1/lab7_1.gen/sources_1/bd/mb_lab7_1/mb_lab7_1_ooc.xdc
