create_clock -period 10.000 -name clk_100 -waveform {0.000 5.000} [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS25 [get_ports rst]
set_property PACKAGE_PIN N15 [get_ports clk]
set_property PACKAGE_PIN J2 [get_ports rst]

set_property -dict {PACKAGE_PIN J1 IOSTANDARD LVCMOS25} [get_ports run]
set_property -dict {PACKAGE_PIN G2 IOSTANDARD LVCMOS25} [get_ports continue_i]
set_property -dict {PACKAGE_PIN H2 IOSTANDARD LVCMOS25} [get_ports frame_done]

#HDMI Signals
set_property -dict {PACKAGE_PIN V17 IOSTANDARD TMDS_33} [get_ports hdmi_clk_n]
set_property -dict {PACKAGE_PIN U16 IOSTANDARD TMDS_33} [get_ports hdmi_clk_p]

set_property -dict {PACKAGE_PIN U18 IOSTANDARD TMDS_33} [get_ports {hdmi_tx_n[0]}]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD TMDS_33} [get_ports {hdmi_tx_n[1]}]
set_property -dict {PACKAGE_PIN T14 IOSTANDARD TMDS_33} [get_ports {hdmi_tx_n[2]}]

set_property -dict {PACKAGE_PIN U17 IOSTANDARD TMDS_33} [get_ports {hdmi_tx_p[0]}]
set_property -dict {PACKAGE_PIN R16 IOSTANDARD TMDS_33} [get_ports {hdmi_tx_p[1]}]
set_property -dict {PACKAGE_PIN R14 IOSTANDARD TMDS_33} [get_ports {hdmi_tx_p[2]}]


set_property MARK_DEBUG true [get_nets buffer_select]
set_property MARK_DEBUG true [get_nets {addra[14]}]
set_property MARK_DEBUG true [get_nets {addra[11]}]
set_property MARK_DEBUG true [get_nets {addra[10]}]
set_property MARK_DEBUG true [get_nets {addra[9]}]
set_property MARK_DEBUG true [get_nets {addra[8]}]
set_property MARK_DEBUG true [get_nets {addra[7]}]
set_property MARK_DEBUG true [get_nets {addra[6]}]
set_property MARK_DEBUG true [get_nets {addrb[17]}]
set_property MARK_DEBUG true [get_nets {addrb[12]}]
set_property MARK_DEBUG true [get_nets {addrb[11]}]
set_property MARK_DEBUG true [get_nets {addrb[10]}]
set_property MARK_DEBUG true [get_nets {addrb[1]}]
set_property MARK_DEBUG true [get_nets {addrb[16]}]
set_property MARK_DEBUG true [get_nets {addrb[4]}]
set_property MARK_DEBUG true [get_nets {addrb[3]}]
set_property MARK_DEBUG true [get_nets {addrb[14]}]
set_property MARK_DEBUG true [get_nets {addrb[13]}]
set_property MARK_DEBUG true [get_nets {addrb[9]}]
set_property MARK_DEBUG true [get_nets {addrb[8]}]
set_property MARK_DEBUG true [get_nets {addrb[5]}]
set_property MARK_DEBUG true [get_nets {addrb[2]}]
set_property MARK_DEBUG true [get_nets {addrb[15]}]
set_property MARK_DEBUG true [get_nets {addrb[7]}]
set_property MARK_DEBUG true [get_nets {addrb[6]}]
set_property MARK_DEBUG true [get_nets {U[1]}]
set_property MARK_DEBUG true [get_nets {U[2]}]
set_property MARK_DEBUG true [get_nets {U[3]}]
set_property MARK_DEBUG true [get_nets {U[4]}]
set_property MARK_DEBUG true [get_nets {buf_plt[0]}]
set_property MARK_DEBUG true [get_nets {buf_plt[1]}]
set_property MARK_DEBUG true [get_nets {buf_plt[2]}]
set_property MARK_DEBUG true [get_nets {buf_plt[3]}]
set_property MARK_DEBUG true [get_nets frame_done_IBUF]
set_property MARK_DEBUG true [get_nets run_IBUF]
